import React, {useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams} from 'react-router-dom'
import {ArrowLeft, ArrowRight, BookOpen, Check, ChevronLeft, ChevronRight, Download, Expand, FileText, Filter, Library, LockKeyhole, Menu, Search, ShoppingBag, SlidersHorizontal, Sparkles, X, ZoomIn} from 'lucide-react'
import research from './data/research.json'
import learning from './data/learning.json'
import categories from './data/categories.json'
import {BRAND, DISCLAIMER} from './config'
import './styles.css'

const money = n => n ? `Rp${n.toLocaleString('id-ID')}` : 'Gratis'

function Header(){const [open,setOpen]=useState(false); return <header><div className="shell header-inner"><Link className="brand" to="/"><span>SN</span>{BRAND}</Link><nav className={open?'open':''} aria-label="Navigasi utama"><NavLink to="/explore/research">Research</NavLink><NavLink to="/explore/learning">Learn</NavLink><NavLink to="/collection/Oil%20%26%20Gas">Collections</NavLink><NavLink to="/library">My Library</NavLink></nav><div className="header-actions"><Link className="icon-btn desktop-search" to="/explore/all" aria-label="Cari"><Search size={20}/></Link><button className="icon-btn menu-btn" onClick={()=>setOpen(!open)} aria-label="Buka menu">{open?<X/>:<Menu/>}</button></div></div></header>}
function StatusBadge({status,period}){return <span className={`status ${status.toLowerCase()}`}>{status==='ARCHIVE'?'ARCHIVE · '+(period||'data lama'):status}</span>}
function PriceBadge({item}){return <span className={`price ${item.isFree?'free':''}`}>{item.isFree?'FREE':money(item.price)}</span>}
function Cover({item,type='research'}){return <div className={`cover ${item.cover}`} aria-hidden="true"><span>{type==='research'?item.ticker:'STUDY NOTES'}</span><div><small>{type==='research'?'COMPANY RESEARCH':'LEARNING SERIES'}</small><b>{item.title}</b></div><i>{item.sector}</i></div>}
function ProductActions({item,type,onBuy}){return <div className="card-actions"><Link className="button ghost small" to={`/detail/${type}/${item.id}?preview=1`}>{type==='research'?'Preview':'Preview Materi'}</Link><Link className="button ghost small" to={`/detail/${type}/${item.id}`}>Lihat Detail</Link>{item.isFree?<button className="button primary small"><Download size={15}/> Download Gratis</button>:<button className="button primary small" onClick={()=>onBuy?.(item,type)}><ShoppingBag size={15}/> Beli PDF</button>}</div>}
function ResearchCard({item,onBuy}){return <article className="product-card"><Cover item={item}/><div className="card-body"><div className="badge-row"><StatusBadge status={item.status} period={item.latestDataPeriod}/><PriceBadge item={item}/></div><p className="eyebrow">RESEARCH · {item.sector}</p><h3>{item.ticker} — {item.title}</h3><p className="company">{item.company}</p><p className="desc">{item.description}</p><div className="facts"><span>{item.latestDataPeriod}</span><span>{item.pages} halaman</span><span>{item.analysisDate}</span></div><div className="tags">{item.tags.slice(0,4).map(x=><span key={x}>{x}</span>)}</div><ProductActions item={item} type="research" onBuy={onBuy}/></div></article>}
function LearningCard({item,onBuy}){return <article className="product-card learning-card"><Cover item={item} type="learning"/><div className="card-body"><div className="badge-row"><StatusBadge status={item.status}/><PriceBadge item={item}/></div><p className="eyebrow">LEARNING · {item.sector}</p><h3>{item.title}</h3><div className="level"><BookOpen size={14}/> {item.level} <i/> {item.series} <i/> {item.pages} halaman</div><p className="desc">{item.description}</p><div className="tags">{item.topics.map(x=><span key={x}>{x}</span>)}</div><ProductActions item={item} type="learning" onBuy={onBuy}/></div></article>}
function SearchBar({value='',onChange,onSubmit}){return <form className="searchbar" onSubmit={e=>{e.preventDefault();onSubmit?.()}} role="search"><Search/><input aria-label="Pencarian" value={value} onChange={e=>onChange?.(e.target.value)} placeholder="Cari emiten, sektor, atau materi..."/><button>Cari</button></form>}
function CategoryChips({active='Semua'}){return <div className="chips" aria-label="Kategori">{categories.map(c=><Link className={active===c.name?'active':''} key={c.name} to={c.name==='Semua'?'/explore/all':`/collection/${encodeURIComponent(c.name)}`}>{c.name}</Link>)}</div>}
function Section({kicker,title,note,children,link}){return <section className="section shell"><div className="section-head"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2>{note&&<p>{note}</p>}</div>{link&&<Link to={link}>Lihat semua <ArrowRight size={17}/></Link>}</div>{children}</section>}
// Future phase: replace this UI-only transition with server-side payment verification,
// protected storage, access records, and an expiring signed download URL.
function PurchaseModal({item,onClose,onUnlock}){if(!item)return null; return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="checkout" onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={onClose} aria-label="Tutup"><X/></button><div className="modal-icon"><LockKeyhole/></div><p className="eyebrow">DUMMY CHECKOUT</p><h2 id="checkout">Sedikit lagi.</h2><p>{item.title}</p><div className="checkout-price"><span>Total</span><b>{money(item.price)}</b></div><p className="fine">Simulasi frontend — tidak ada pembayaran yang diproses.</p><button className="button primary wide" onClick={onUnlock}>Lanjut Pembayaran <ArrowRight size={18}/></button></div></div>}
function useCheckout(){const [buy,setBuy]=useState(null); const navigate=useNavigate(); return {modal:<PurchaseModal item={buy?.item} onClose={()=>setBuy(null)} onUnlock={()=>navigate(`/detail/${buy.type}/${buy.item.id}?unlocked=1`)}/>,buy:(item,type)=>setBuy({item,type})}}

function Home(){const [q,setQ]=useState(''); const nav=useNavigate(); const check=useCheckout(); return <>{check.modal}<main><section className="hero"><div className="shell hero-inner"><div className="hero-copy"><p className="pill"><Sparkles size={15}/> Research, tapi lebih ramah.</p><h1>Baca Saham Tanpa Bikin Kepala Tambah Pusing.</h1><p>Kumpulan catatan riset saham, bedah emiten, dan materi belajar investasi dalam format yang lebih terstruktur.</p><SearchBar value={q} onChange={setQ} onSubmit={()=>nav('/explore/all?q='+encodeURIComponent(q))}/><small>Contoh: MEDC, Oil & Gas, atau Reserve</small></div><div className="hero-art" aria-hidden="true"><div className="sun">✦</div><div className="book b1">MEDC<br/><span>Deep Dive</span></div><div className="book b2">Oil & Gas<br/><span>from zero</span></div><div className="note">Kenali bisnisnya<br/>sebelum valuasinya. ↗</div></div></div></section><section className="shell nav-cards"><Link to="/explore/research" className="nav-card bluebox"><div><FileText/></div><span><small>01 · RESEARCH</small><h2>Analisis Saham</h2><p>Kumpulan bedah emiten berdasarkan bisnis, fundamental, risiko, narasi, dan data terbaru.</p><b>Lihat Analisis <ArrowRight/></b></span></Link><Link to="/explore/learning" className="nav-card yellowbox"><div><BookOpen/></div><span><small>02 · LEARNING</small><h2>Materi Belajar</h2><p>Belajar memahami bisnis dan fundamental saham dari dasar berdasarkan sektor.</p><b>Mulai Belajar <ArrowRight/></b></span></Link></section><section className="shell category-wrap"><p className="eyebrow">JELAJAHI PER SEKTOR</p><CategoryChips/></section><Section kicker="BARU DI RAK" title="Latest Research" note="Data berubah. Analisis juga harus ikut berubah." link="/explore/research"><div className="horizontal-grid">{research.slice(0,3).map(x=><ResearchCard key={x.id} item={x} onBuy={check.buy}/>)}</div></Section><Section kicker="MULAI PELAN-PELAN" title="Belajar dari Nol" note="Mulai dari yang gampang dulu." link="/explore/learning"><div className="horizontal-grid">{learning.filter(x=>x.level==='Pemula').map(x=><LearningCard key={x.id} item={x} onBuy={check.buy}/>)}</div></Section><Section kicker="PILIH JALURMU" title="Popular Collections"><div className="collection-grid">{categories.slice(1,5).map((c,i)=><Link to={`/collection/${encodeURIComponent(c.name)}`} className={`collection c${i}`} key={c.name}><span>0{i+1}</span><h3>{c.name}</h3><p>{c.description}</p><ArrowRight/></Link>)}</div></Section><Section kicker="MASIH HANGAT" title="Recently Updated" note="Baca seperlunya, jangan bikin kepala panas." link="/explore/all"><div className="update-strip">{research.filter(x=>x.status==='UPDATED').slice(0,3).map(x=><Link key={x.id} to={`/detail/research/${x.id}`}><StatusBadge status={x.status}/><b>{x.ticker} · {x.title}</b><span>{x.analysisDate}</span><ChevronRight/></Link>)}</div></Section></main></>}

function FilterDrawer({filters,setFilters,onClose}){return <div className="filter-panel"><div><h3><SlidersHorizontal/> Filter</h3><button className="icon-btn" onClick={onClose}><X/></button></div>{[['Content Type','type',['Semua','Research','Learning']],['Sector','sector',categories.map(x=>x.name)],['Akses','access',['Semua','Gratis','Berbayar']],['Latest Update','status',['Semua','NEW','UPDATED','ARCHIVE']],['Learning Level','level',['Semua','Pemula','Menengah','Lanjutan']]].map(([label,key,opts])=><label key={key}>{label}<select value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}>{opts.map(x=><option key={x}>{x}</option>)}</select></label>)}<button className="button primary wide" onClick={onClose}>Terapkan Filter</button></div>}
function Explore(){const {type='all'}=useParams(); const params=new URLSearchParams(location.search); const [q,setQ]=useState(params.get('q')||''); const [drawer,setDrawer]=useState(false); const [filters,setFilters]=useState({type:type==='all'?'Semua':type==='research'?'Research':'Learning',sector:'Semua',access:'Semua',status:'Semua',level:'Semua'}); const check=useCheckout(); const items=useMemo(()=>[...research.map(x=>({...x,_type:'research'})),...learning.map(x=>({...x,_type:'learning'}))].filter(x=>{let hay=[x.ticker,x.company,x.title,x.sector,...(x.tags||[]),...(x.topics||[])].join(' ').toLowerCase(); return hay.includes(q.toLowerCase())&&(filters.type==='Semua'||x.contentType===filters.type||(filters.type==='Learning'&&x._type==='learning'))&&(filters.sector==='Semua'||x.sector===filters.sector)&&(filters.access==='Semua'||(filters.access==='Gratis')===x.isFree)&&(filters.status==='Semua'||x.status===filters.status)&&(filters.level==='Semua'||x.level===filters.level)}),[q,filters]); return <main className="page shell">{check.modal}<div className="page-title"><p className="eyebrow">THE LIBRARY</p><h1>{type==='research'?'Analisis Saham':type==='learning'?'Materi Belajar':'Semua Koleksi'}</h1><p>Temukan catatan yang pas. Tidak perlu membaca semuanya sekaligus.</p></div><div className="search-filter"><SearchBar value={q} onChange={setQ}/><button className="button filter-btn" onClick={()=>setDrawer(!drawer)}><Filter/> Filter</button>{drawer&&<FilterDrawer filters={filters} setFilters={setFilters} onClose={()=>setDrawer(false)}/>}</div><CategoryChips active={filters.sector}/><p className="result-count">{items.length} materi ditemukan</p>{items.length?<div className="catalog-grid">{items.map(x=>x._type==='research'?<ResearchCard item={x} key={x.id} onBuy={check.buy}/>:<LearningCard item={x} key={x.id} onBuy={check.buy}/>)}</div>:<EmptyState/>}</main>}
function EmptyState(){return <div className="empty"><Library/><h2>Belum ada riset di kategori ini.</h2><p>Materi sedang disusun. Coba longgarkan filter atau jelajahi koleksi lain.</p><Link className="button primary" to="/explore/all">Lihat semua koleksi</Link></div>}

function PDFPreview({item,unlocked,onUnlock}){const [page,setPage]=useState(1), max=item.isFree||unlocked?item.pages:3; return <div className="pdf"><div className="pdf-toolbar"><span>Page {page} / {item.pages}</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)} aria-label="Halaman sebelumnya"><ChevronLeft/></button><button disabled={page===max} onClick={()=>setPage(p=>p+1)} aria-label="Halaman berikutnya"><ChevronRight/></button><button aria-label="Perbesar"><ZoomIn/></button><button aria-label="Layar penuh"><Expand/></button></div></div><div className="paper"><p>STOCK NOTES / {item.sector.toUpperCase()}</p><h2>{item.title}</h2><div className="paper-line wide"/><div className="paper-line"/><div className="paper-chart"><i/><i/><i/><i/><i/></div><h4>{page===1?'The simple view':page===2?'What drives the business':'A closer look'}</h4><div className="paper-line wide"/><div className="paper-line wide"/><div className="paper-line short"/><b className="page-no">{page}</b>{!item.isFree&&!unlocked&&page===max&&<div className="locked"><LockKeyhole/><h3>Lanjut membaca versi lengkap</h3><p>Preview berhenti di halaman {max}. Unlock untuk membaca seluruh materi.</p><button className="button primary" onClick={onUnlock}>Unlock PDF</button></div>}</div><p className="preview-note">Preview placeholder · Isi lengkap PDF tidak ditampilkan pada prototype.</p></div>}
function ResearchMetadata({item,type,unlocked,onBuy}){return <aside className="metadata"><div className="badge-row"><span className="type-badge">{type==='research'?'RESEARCH':'LEARNING'}</span><StatusBadge status={item.status} period={item.latestDataPeriod}/></div><h1>{type==='research'&&<>{item.ticker} — </>}{item.title}</h1>{type==='research'&&<p className="company">{item.company}</p>}<p className="desc">{item.description}</p><dl>{type==='research'?<><div><dt>Sektor</dt><dd>{item.sector}</dd></div><div><dt>Tanggal analisis</dt><dd>{item.analysisDate}</dd></div><div><dt>Data terakhir</dt><dd>{item.latestDataPeriod}</dd></div><div><dt>Mode riset</dt><dd>{item.analysisMode}</dd></div><div><dt>Probability of truth</dt><dd>{item.probabilityOfTruth}</dd></div></>:<><div><dt>Kategori</dt><dd>{item.sector}</dd></div><div><dt>Level</dt><dd>{item.level}</dd></div><div><dt>Series</dt><dd>{item.series}</dd></div></>}<div><dt>Jumlah halaman</dt><dd>{item.pages} halaman</dd></div></dl><div className="tags">{(item.tags||item.topics).map(x=><span key={x}>{x}</span>)}</div><div className="buy-row"><strong>{money(item.price)}</strong>{item.isFree||unlocked?<button className="button primary"><Download/> {item.isFree?'Download Gratis':'Download PDF'}</button>:<button className="button primary" onClick={onBuy}><ShoppingBag/> Beli PDF — {money(item.price)}</button>}</div>{unlocked&&<p className="unlocked"><Check/> Purchased / unlocked (simulasi)</p>}</aside>}
function Detail(){const {type,id}=useParams(); const item=(type==='research'?research:learning).find(x=>x.id===id); const unlocked=new URLSearchParams(location.search).get('unlocked')==='1'; const check=useCheckout(); if(!item)return <EmptyState/>; return <main className="detail shell">{check.modal}<Link className="back" to="/explore/all"><ArrowLeft/> Kembali ke library</Link><div className="detail-layout"><ResearchMetadata item={item} type={type} unlocked={unlocked} onBuy={()=>check.buy(item,type)}/><PDFPreview item={item} unlocked={unlocked} onUnlock={()=>check.buy(item,type)}/></div><section className="inside"><p className="eyebrow">DAFTAR BAHASAN</p><h2>What's Inside</h2><p>Gambaran isi supaya kamu tahu apa yang akan dipelajari—tanpa membocorkan seluruh PDF.</p><div>{(type==='research'?['Business Overview','Financial Performance','Growth Drivers','Debt','Reserve & Assets','Key Risks','Valuation','Conclusion']:['Konsep Dasar','Cara Kerja Bisnis','Metrik Penting','Contoh Praktis','Latihan Membaca Data','Ringkasan']).map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div></section><div className="disclaimer"><b>Catatan penting</b><p>{DISCLAIMER}</p></div></main>}
function Collection(){const {sector}=useParams(); const rs=research.filter(x=>x.sector===sector), ls=learning.filter(x=>x.sector===sector); const check=useCheckout(); return <main className="page shell">{check.modal}<div className="collection-hero"><p className="eyebrow">SECTOR COLLECTION</p><h1>{sector}</h1><p>{categories.find(x=>x.name===sector)?.description||'Koleksi riset dan materi belajar dalam satu rak.'}</p><span>Kenali industrinya, baru baca emitennya.</span></div><CategoryChips active={sector}/><Section kicker="BEDAH EMITEN" title="Research" note={`${rs.length} catatan tersedia`}>{rs.length?<div className="catalog-grid">{rs.map(x=><ResearchCard key={x.id} item={x} onBuy={check.buy}/>)}</div>:<EmptyState/>}</Section><Section kicker="BANGUN FONDASI" title="Learning Materials" note="Mulai dari yang gampang dulu.">{ls.length?<div className="catalog-grid">{ls.map(x=><LearningCard key={x.id} item={x} onBuy={check.buy}/>)}</div>:<EmptyState/>}</Section></main>}
function MyLibrary(){return <main className="page shell"><div className="page-title"><p className="eyebrow">MY ACCESS · PROTOTYPE</p><h1>My Library</h1><p>Semua yang sudah dibuka, rapi di satu tempat. Belum menggunakan autentikasi sungguhan.</p></div>{[['Purchased Research',[research[0]]],['Free Downloads',research.filter(x=>x.isFree).slice(0,2)],['Learning Materials',[learning[0]]]].map(([name,items])=><Section key={name} kicker="YOUR SHELF" title={name}><div className="library-list">{items.map(x=><Link key={x.id} to={`/detail/${x.ticker?'research':'learning'}/${x.id}?unlocked=1`}><div className={`mini-cover ${x.cover}`}><FileText/></div><span><b>{x.ticker&&x.ticker+' · '}{x.title}</b><small>{x.sector} · {x.pages} halaman</small></span><span className="access"><Check/> Unlocked</span><ChevronRight/></Link>)}</div></Section>)}</main>}
function Disclaimer(){return <main className="page shell prose"><p className="eyebrow">PLEASE READ</p><h1>Disclaimer</h1><h2>Materi edukasi, bukan rekomendasi.</h2><p>{DISCLAIMER}</p><p>Seluruh konten pada prototype ini adalah data sample dan placeholder. Nama perusahaan dan ticker digunakan hanya untuk mendemonstrasikan struktur antarmuka, bukan sebagai analisis atau pendapat investasi aktual.</p><h2>Keputusan tetap milik pembaca.</h2><p>Lakukan riset mandiri dan pertimbangkan profil risiko sebelum membuat keputusan investasi. Kinerja masa lalu tidak menjamin hasil di masa depan.</p></main>}
function Footer(){return <footer><div className="shell footer-grid"><div><Link className="brand" to="/"><span>SN</span>{BRAND}</Link><p>Baca bisnisnya. Susun pemahamannya.<br/>Jangan bikin kepala panas.</p></div><div><b>Explore</b><Link to="/explore/research">Research</Link><Link to="/explore/learning">Learning</Link><Link to="/library">My Library</Link></div><div><b>Info</b><Link to="/disclaimer">Disclaimer</Link><a href="mailto:hello@example.com">Contact</a></div></div><div className="shell footnote"><p>{DISCLAIMER}</p><span>© 2026 {BRAND} · Prototype</span></div></footer>}
function App(){return <><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/explore/:type" element={<Explore/>}/><Route path="/detail/:type/:id" element={<Detail/>}/><Route path="/collection/:sector" element={<Collection/>}/><Route path="/library" element={<MyLibrary/>}/><Route path="/disclaimer" element={<Disclaimer/>}/></Routes><Footer/></>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>)
